import Head from 'next/head';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import About from '../components/About';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import Footer from '../components/Footer';


export default function Home() {
  return (
      <>
      <Head>
        <title>New Portfolio 2022 - Rizaldy Parera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
    
          <Navbar />
          <Hero />
          <About />
          <Projects />
          <Contact />
          <Footer />
      </>
  )
}
